### ISSUE TITLE
Ошибки компиляции проекта

### ISSUE THREAD

**Issue by smkonst** [kotyara12/telemeter_dzen#7]
По ключу configENABLE_BACKWARD_COMPATIBILITY нашёл в документации ESP-IDF, что служит для включения обратной совместимости с API до FreeRTOS v8.0.0. 
Установил этот параметр в sdkconfig.esp32dev с помощью menuconfig. Ошибка с xSemaphoreHandle исчезла и компиляция пошла дальше. 
Отсюда напрашивается ответ на Ваш вопрос. Поскольку Вы проект делали давно, то и свои библиотеки делали, скорее всего, для старой версии FreeRTOS. А я только начинаю. Установку VS Code и PlatformIO делал по Вашим статьям неделю назад. И, поэтому, у меня версии исходных файлов для сборки проекта могу отличаться от Ваших.
Вот и последняя ошибка компилятора меня «вырубила»:
C:/PlatformIO/libs/system/reEsp32/src/reEsp32.cpp:20:10: fatal error: soc/cpu.h: No such file or directory
   20 | #include "soc/cpu.h"
      |          ^~~~~~~~~~~
compilation terminated.
Действительно, файла cpu.h в исходниках я не нашёл. Есть файл esp_cpu.h, расположенный в папке C:\.platformio\packages\framework-espidf\components\esp_hw_support\include. Но это то, что нужно или совсем другой файл?
Попробовал подменить, полезли другие ошибки. Вернул назад.
Спасибо за Ваши ответы. Буду ждать обновлённый архив на GitHub.

**Comment by kotyara12** [comment]
Добрый день!
Архив обновлен, ветка 03_ESP-IDF_5-0-0, этот архив одинаково работает и со старой и с новой (5.0.0) версиями фреймворка. 
Но будьте внимательны - в новой версии пока есть не пофиксенные проблемы
